name: Daily Zurich Report

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run script
        run: python report_generator.py

      - name: Commit and push index.html
        run: |
          git config --global user.name "cathyshing12"
          git config --global user.email "cathyshing12@users.noreply.github.com"
          git add index.html
          git commit -m "Auto-update daily report" || echo "No changes to commit"
          git push
